name: dashboard_challenge
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^7.2.0

  # Value equality
  equatable: ^2.0.3

  # API calls
  http: ^0.13.3

  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Tests
  bloc_test: ^8.1.0

 
flutter:

  uses-material-design: true

  assets:
   - assets/fonts/
   - assets/icons/
  
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf